### ISSUE TITLE
Mac OSX/Linux Instructions

### ISSUE THREAD

**Issue by jsimonson2013** [Madison-SDC/360WebViewer#3]
I have only tested the project on Windows 10 and it would be nice to make sure that Mac and Linux users are able to contribute to the project.

**Comment by MatthewTDuff** [comment]
I'll play with it on Ubuntu later this week.

**Comment by jmilk13** [comment]
I'll work on OSX

**Comment by eschlossberg** [comment]
It's been working so far for me on Ubuntu just as well as it does on Windows 10.

**Comment by jmilk13** [comment]
Working so far on OSX

**Comment by jsimonson2013** [comment]
Since the install instructions work for OSX and Ubuntu, I am going to close this issue.
